services:
  - type: web
    name: doc-sync-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LIBREOFFICE_PATH
        value: /usr/bin/libreoffice